@extends('layouts.storefront')
@section('title','Sign In — Chacha Prime')
@push('styles')
<style>
.cp-auth{min-height:calc(100vh - 104px);background:#f5f7fb;padding:28px 16px 42px}.cp-auth-wrap{width:min(1050px,100%);margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:24px;overflow:hidden;box-shadow:0 24px 70px #0f172a14;display:grid;grid-template-columns:42% 58%}.cp-auth-visual{background:linear-gradient(160deg,#071426,#102a52);color:#fff;padding:42px;position:relative;overflow:hidden}.cp-auth-visual:after{content:"";position:absolute;inset:auto -80px -110px auto;width:300px;height:300px;border-radius:50%;background:#2563eb22}.cp-auth-logo{width:205px;height:58px;object-fit:contain;object-position:left center;display:block}.cp-auth-visual h2{font-size:31px;letter-spacing:-.9px;margin:55px 0 9px}.cp-auth-visual p{color:#cbd5e1;line-height:1.7;font-size:12px;max-width:320px}.cp-auth-points{display:grid;gap:9px;margin-top:24px}.cp-auth-point{padding:11px 12px;border:1px solid #ffffff16;background:#ffffff09;border-radius:11px;font-size:11px;color:#e2e8f0}.cp-auth-form{padding:42px}.cp-auth-topline{height:1px;background:#e5e7eb;margin-bottom:24px}.cp-auth-eyebrow{font-size:10px;font-weight:900;letter-spacing:1.8px;color:#2563eb}.cp-auth-form h1{margin:7px 0 5px;font-size:30px;color:#0f172a}.cp-auth-lead{color:#64748b;font-size:12px;line-height:1.6;margin:0}.cp-auth-notice{padding:11px 13px;border-radius:10px;font-size:11px;margin:15px 0}.cp-auth-success{background:#ecfdf3;color:#027a48;border:1px solid #abefc6}.cp-auth-error{background:#fef3f2;color:#b42318;border:1px solid #fecdca}.cp-auth-tabs{display:grid;grid-template-columns:1fr 1fr;background:#f1f5f9;border-radius:10px;padding:3px;margin:20px 0 14px}.cp-auth-tab{border:0;background:transparent;padding:10px;border-radius:8px;font-size:11px;font-weight:900;color:#64748b;cursor:pointer}.cp-auth-tab.active{background:#fff;color:#0f172a;box-shadow:0 2px 8px #0f172a10}.cp-auth-panel{display:none}.cp-auth-panel.active{display:block}.cp-auth-form form{display:grid;gap:13px}.cp-field{display:grid;gap:6px;font-size:11px;font-weight:800;color:#334155}.cp-field input{width:100%;padding:13px;border:1px solid #dbe1e8;border-radius:11px;font-size:13px;outline:none}.cp-field input:focus{border-color:#2563eb;box-shadow:0 0 0 3px #2563eb14}.cp-auth-btn{border:0;border-radius:11px;padding:13px;background:#0f172a;color:#fff;font-weight:900;cursor:pointer}.cp-auth-btn:hover{background:#172554}.cp-auth-foot{text-align:center;color:#64748b;font-size:12px;margin:20px 0 0}.cp-auth-foot a{color:#2563eb;font-weight:900;text-decoration:none}.cp-auth-mini{margin-top:12px;color:#94a3b8;font-size:10px;text-align:center}@media(max-width:760px){.cp-auth{padding:14px 10px 28px}.cp-auth-wrap{grid-template-columns:1fr}.cp-auth-visual{padding:25px}.cp-auth-visual h2{margin-top:25px}.cp-auth-points{display:none}.cp-auth-form{padding:25px 20px}}
</style>
@endpush
@section('content')
<section class="cp-auth"><div class="cp-auth-wrap">
<div class="cp-auth-visual"><img class="cp-auth-logo" src="{{asset('images/chacha-logo.svg')}}" alt="CHACHA 查查 Prime"><h2>Welcome back.</h2><p>Sign in and continue your Chacha Prime marketplace journey with secure role-based access.</p><div class="cp-auth-points"><div class="cp-auth-point">✓ Email verification code</div><div class="cp-auth-point">✓ Google Authenticator / TOTP</div><div class="cp-auth-point">✓ Customer, Seller & Business accounts</div></div></div>
<div class="cp-auth-form"><div class="cp-auth-topline"></div><span class="cp-auth-eyebrow">SECURE ACCOUNT ACCESS</span><h1>Sign in</h1><p class="cp-auth-lead">Choose password login or request a one-time email verification code.</p>
@if(session('success'))<div class="cp-auth-notice cp-auth-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="cp-auth-notice cp-auth-error">{{$errors->first()}}</div>@endif
<div class="cp-auth-tabs"><button type="button" class="cp-auth-tab active" data-auth-tab="password">Password</button><button type="button" class="cp-auth-tab" data-auth-tab="otp">OTP Login</button></div>
<div class="cp-auth-panel active" data-auth-panel="password"><form method="POST" action="{{route('auth.login.submit')}}">@csrf<label class="cp-field">Email<input type="email" name="email" value="{{old('email')}}" autocomplete="email" required></label><label class="cp-field">Password<input type="password" name="password" autocomplete="current-password" required></label><button class="cp-auth-btn" type="submit">Sign in securely →</button></form></div>
<div class="cp-auth-panel" data-auth-panel="otp"><form method="POST" action="{{route('auth.otp.login')}}">@csrf<label class="cp-field">Email<input type="email" name="email" autocomplete="email" required></label><button class="cp-auth-btn" type="submit">Get OTP →</button><div class="cp-auth-mini">We will email a 6-digit verification code before the authenticator step.</div></form></div>
<p class="cp-auth-foot">New to Chacha Prime? <a href="{{route('auth.register')}}">Create an account</a></p></div></div></section>
@endsection
@push('scripts')
<script>
document.querySelectorAll('[data-auth-tab]').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('[data-auth-panel]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('[data-auth-panel="'+btn.dataset.authTab+'"]').classList.add('active');});});
</script>
@endpush