@extends('layouts.storefront')
@section('title','Verify Email — Chacha Prime')
@push('styles')
<style>
.cp-auth-step{min-height:calc(100vh - 104px);background:#f5f7fb;padding:34px 16px}.cp-step-card{width:min(500px,100%);margin:18px auto;background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:34px;box-shadow:0 24px 70px #0f172a14}.cp-step-brand{height:48px;display:flex;justify-content:center;margin-bottom:16px}.cp-step-brand img{height:48px;width:190px;object-fit:contain;filter:invert(1)}.cp-step-line{height:1px;background:#e5e7eb;margin-bottom:24px}.cp-step-icon{width:54px;height:54px;border-radius:16px;background:#eff6ff;color:#2563eb;display:grid;place-items:center;font-size:24px;margin:0 auto 16px}.cp-step-card{text-align:center}.cp-step-card .eyebrow{font-size:10px;font-weight:900;letter-spacing:1.8px;color:#2563eb}.cp-step-card h1{margin:7px 0;font-size:27px;color:#0f172a}.cp-step-card p{color:#64748b;font-size:12px;line-height:1.6}.cp-step-notice{padding:11px 13px;border-radius:10px;font-size:11px;margin:14px 0;text-align:left}.cp-step-error{background:#fef3f2;color:#b42318;border:1px solid #fecdca}.cp-step-success{background:#ecfdf3;color:#027a48;border:1px solid #abefc6}.cp-step-form{display:grid;gap:12px;margin-top:20px}.cp-otp-input{letter-spacing:8px;text-align:center;font-size:23px!important;font-weight:900}.cp-step-form input{width:100%;padding:13px;border:1px solid #dbe1e8;border-radius:11px;outline:none}.cp-step-form input:focus{border-color:#2563eb;box-shadow:0 0 0 3px #2563eb14}.cp-step-btn{border:0;border-radius:11px;padding:13px;background:#0f172a;color:#fff;font-weight:900;cursor:pointer}.cp-step-foot{margin-top:17px;font-size:11px}.cp-step-foot a{color:#2563eb;font-weight:800;text-decoration:none}
</style>
@endpush
@section('content')
<section class="cp-auth-step"><div class="cp-step-card"><div class="cp-step-brand"><img src="{{asset('images/chacha-logo.svg')}}" alt="CHACHA 查查 Prime"></div><div class="cp-step-line"></div><div class="cp-step-icon">✉</div><span class="eyebrow">SECURITY STEP 1</span><h1>Verify your email</h1><p>Enter the 6-digit code we sent to your email address before continuing to authenticator verification.</p>
@if($errors->any())<div class="cp-step-notice cp-step-error">@foreach($errors->all() as $error)<div>{{$error}}</div>@endforeach</div>@endif
@if(session('success'))<div class="cp-step-notice cp-step-success">{{session('success')}}</div>@endif
<form class="cp-step-form" method="POST" action="{{route('auth.otp.verify')}}">@csrf<input class="cp-otp-input" name="code" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" autocomplete="one-time-code" required autofocus placeholder="••••••"><button class="cp-step-btn" type="submit">Verify OTP →</button></form>
<div class="cp-step-foot"><a href="{{route('auth.login')}}">← Back to login</a></div></div></section>
@endsection