@extends('layouts.storefront')
@section('title','Create Account — Chacha Prime')
@push('styles')
<style>
.cp-reg{min-height:calc(100vh - 104px);background:#f5f7fb;padding:28px 16px 42px}.cp-reg-wrap{width:min(1080px,100%);margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:24px;overflow:hidden;box-shadow:0 24px 70px #0f172a14}.cp-reg-head{background:linear-gradient(160deg,#071426,#102a52);padding:28px 34px;color:#fff;display:flex;align-items:center;gap:22px}.cp-reg-logo{width:190px;height:55px;object-fit:contain;object-position:left center;flex:0 0 auto}.cp-reg-head h1{margin:0;font-size:26px}.cp-reg-head p{margin:5px 0 0;color:#cbd5e1;font-size:11px}.cp-reg-body{padding:30px 34px}.cp-reg-line{height:1px;background:#e5e7eb;margin-bottom:24px}.cp-reg-eyebrow{font-size:10px;font-weight:900;letter-spacing:1.8px;color:#2563eb}.cp-reg-intro{color:#64748b;font-size:12px}.cp-reg-notice{padding:11px;border-radius:10px;font-size:11px;background:#fef3f2;color:#b42318;border:1px solid #fecdca;margin:12px 0}.cp-reg-roles{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin:18px 0}.cp-reg-role{position:relative;border:1px solid #dbe1e8;border-radius:14px;padding:16px;cursor:pointer;background:#fff;transition:.15s}.cp-reg-role:hover{border-color:#93c5fd;transform:translateY(-1px)}.cp-reg-role.active{border-color:#2563eb;background:#eff6ff;box-shadow:0 0 0 2px #2563eb18}.cp-reg-role input{position:absolute;opacity:0;pointer-events:none}.cp-reg-role b{display:block;color:#0f172a;font-size:13px}.cp-reg-role span{display:block;color:#64748b;font-size:10px;margin-top:5px;line-height:1.5}.cp-reg-check{position:absolute;right:12px;top:12px;width:17px;height:17px;border:1px solid #cbd5e1;border-radius:50%;background:#fff}.cp-reg-role.active .cp-reg-check{border-color:#2563eb;background:#2563eb;box-shadow:inset 0 0 0 4px #fff}.cp-reg-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cp-reg-field{display:grid;gap:6px;font-size:11px;font-weight:800;color:#334155}.cp-reg-field.full{grid-column:1/-1}.cp-reg-field input{width:100%;padding:12px;border:1px solid #dbe1e8;border-radius:10px;font-size:12px;outline:none}.cp-reg-field input:focus{border-color:#2563eb;box-shadow:0 0 0 3px #2563eb14}.cp-reg-submit{grid-column:1/-1;border:0;background:#0f172a;color:#fff;border-radius:11px;padding:13px;font-weight:900;cursor:pointer}.cp-reg-submit:hover{background:#172554}.cp-reg-foot{text-align:center;color:#64748b;font-size:12px;margin-top:18px}.cp-reg-foot a{color:#2563eb;font-weight:900;text-decoration:none}@media(max-width:720px){.cp-reg-head{align-items:flex-start;flex-direction:column;padding:23px}.cp-reg-body{padding:23px}.cp-reg-roles,.cp-reg-form{grid-template-columns:1fr}.cp-reg-field.full,.cp-reg-submit{grid-column:1}}
</style>
@endpush
@section('content')
<section class="cp-reg"><div class="cp-reg-wrap">
<header class="cp-reg-head"><img class="cp-reg-logo" src="{{asset('images/chacha-logo.svg')}}" alt="CHACHA 查查 Prime"><div><h1>Create your Chacha Prime account</h1><p>Select your marketplace account type and continue to verification.</p></div></header>
<div class="cp-reg-body"><div class="cp-reg-line"></div><span class="cp-reg-eyebrow">JOIN CHACHA PRIME</span><p class="cp-reg-intro">Choose the account type that matches how you will use the marketplace.</p>
@if($errors->any())<div class="cp-reg-notice">@foreach($errors->all() as $error)<div>{{$error}}</div>@endforeach</div>@endif
<form method="POST" action="{{route('auth.register.submit')}}" class="cp-reg-form" id="cpRegisterForm">@csrf
<div class="cp-reg-field full"><span>Account type</span><div class="cp-reg-roles">
<label class="cp-reg-role {{old('type',$type)==='customer'?'active':''}}" data-role-card><input type="radio" name="type" value="customer" @checked(old('type',$type)==='customer')><i class="cp-reg-check"></i><b>B2C Customer</b><span>Retail shopping and personal purchases.</span></label>
<label class="cp-reg-role {{old('type',$type)==='b2b_customer'?'active':''}}" data-role-card><input type="radio" name="type" value="b2b_customer" @checked(old('type',$type)==='b2b_customer')><i class="cp-reg-check"></i><b>B2B Customer</b><span>Business purchasing and quantity-based buying.</span></label>
<label class="cp-reg-role {{old('type',$type)==='vendor'?'active':''}}" data-role-card><input type="radio" name="type" value="vendor" @checked(old('type',$type)==='vendor')><i class="cp-reg-check"></i><b>Vendor / Seller</b><span>Sell products and manage your Seller Center.</span></label>
</div></div>
<label class="cp-reg-field">Full name<input name="name" value="{{old('name')}}" autocomplete="name" required></label><label class="cp-reg-field">Phone<input name="phone" value="{{old('phone')}}" autocomplete="tel"></label>
<label class="cp-reg-field full">Email<input type="email" name="email" value="{{old('email')}}" autocomplete="email" required></label>
<label class="cp-reg-field">Password<input type="password" name="password" autocomplete="new-password" minlength="8" required></label><label class="cp-reg-field">Confirm password<input type="password" name="password_confirmation" autocomplete="new-password" minlength="8" required></label>
<button class="cp-reg-submit" type="submit">Create account & continue →</button></form><div class="cp-reg-foot">Already registered? <a href="{{route('auth.login')}}">Sign in</a></div></div></div></section>
@endsection
@push('scripts')
<script>
document.querySelectorAll('[data-role-card]').forEach(function(card){card.addEventListener('click',function(){document.querySelectorAll('[data-role-card]').forEach(x=>x.classList.remove('active'));card.classList.add('active');const radio=card.querySelector('input[type=radio]');radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));});});
</script>
@endpush