<section class="cp-hero cp-premium-hero" data-cp-carousel>
<div class="cp-hero-track">
<article class="cp-hero-slide hero-market is-active"><div class="cp-hero-copy"><span>CHACHA PRIME • GLOBAL MARKETPLACE</span><h1>Premium shopping.<br><em>Built for everyone.</em></h1><p>Discover trusted sellers, competitive pricing and a seamless B2B &amp; B2C marketplace experience.</p><div class="cp-hero-actions"><a href="{{route('shop')}}">Explore marketplace</a><a class="secondary" href="{{route('group-buying')}}">View group offers</a></div></div><div class="cp-hero-visual"><div class="hero-orbit orbit-one"></div><div class="hero-orbit orbit-two"></div><div class="hero-product-stack"><span>NEW</span><b>CP</b><small>Premium<br>Collection</small></div></div></article>
<article class="cp-hero-slide hero-b2b"><div class="cp-hero-copy"><span>B2B SOURCING • BUSINESS PRICING</span><h1>Buy at scale.<br><em>Grow with confidence.</em></h1><p>Wholesale pricing, quantity tiers and seller-led sourcing for growing businesses.</p><div class="cp-hero-actions"><a href="{{route('shop')}}">Shop B2B</a><a class="secondary" href="{{route('vendor.register')}}">Become a seller</a></div></div><div class="cp-hero-panel"><strong>BUSINESS</strong><b>Wholesale</b><small>Quantity pricing<br>Seller offers<br>Global sourcing</small></div></article>
<article class="cp-hero-slide hero-live"><div class="cp-hero-copy"><span>LIVE COMMERCE • DISCOVER IN REAL TIME</span><h1>Watch. Discover.<br><em>Shop live.</em></h1><p>Meet sellers, see products in action and move from discovery to checkout in one experience.</p><div class="cp-hero-actions"><a href="{{route('live')}}">Watch live</a><a class="secondary" href="{{route('vendor.register')}}">Start streaming</a></div></div><div class="cp-live-card"><i></i><strong>LIVE</strong><b>Seller showcase</b><small>Interactive shopping experience</small></div></article>
<article class="cp-hero-slide hero-group"><div class="cp-hero-copy"><span>GROUP BUYING • BETTER TOGETHER</span><h1>Join the crowd.<br><em>Unlock the offer.</em></h1><p>Participate in active campaigns and discover quantity-driven marketplace deals.</p><div class="cp-hero-actions"><a href="{{route('group-buying')}}">Explore campaigns</a><a class="secondary" href="{{route('shop')}}">Shop products</a></div></div><div class="cp-price-card"><small>GROUP OFFER</small><strong>01 → 10+</strong><b>More participants<br>More opportunity</b></div></article>
<article class="cp-hero-slide hero-deals"><div class="cp-hero-copy"><span>COUPONS • FLASH DEALS • DAILY OFFERS</span><h1>Premium deals.<br><em>Ready when you are.</em></h1><p>Find limited-time offers, seller coupons and marketplace promotions across categories.</p><div class="cp-hero-actions"><a href="{{route('shop')}}?deals=1">Shop deals</a><a class="secondary" href="{{route('shop')}}">Browse all</a></div></div><div class="cp-deal-card"><small>LIMITED OFFER</small><strong>DEALS</strong><b>Coupons + Flash</b></div></article>
<article class="cp-hero-slide hero-sell"><div class="cp-hero-copy"><span>SELL ON CHACHA PRIME • SELLER CENTER</span><h1>Build your store.<br><em>Reach more buyers.</em></h1><p>Manage products, inventory, orders, pricing, live commerce and customer conversations from one Seller Center.</p><div class="cp-hero-actions"><a href="{{route('vendor.register')}}">Start selling</a><a class="secondary" href="{{route('vendor.dashboard')}}">Seller Center</a></div></div><div class="cp-seller-card"><strong>SELLER</strong><b>CONTROL CENTER</b><small>Products • Orders<br>Pricing • Analytics</small></div></article>
</div>
<button class="cp-hero-arrow prev" type="button" data-cp-prev aria-label="Previous banner">‹</button><button class="cp-hero-arrow next" type="button" data-cp-next aria-label="Next banner">›</button><div class="cp-hero-dots" data-cp-dots></div>
</section>