@extends('layouts.customer')
@section('title','Virtual Card — Chacha Prime')
@push('styles')<style>
.cp-vcard{max-width:590px;min-height:270px;border-radius:24px;padding:28px;color:#fff;background:radial-gradient(circle at 85% 15%,#415b78,#0b1220 55%);box-shadow:0 24px 55px rgba(7,17,31,.18);position:relative;overflow:hidden}.cp-vcard:after{content:"";position:absolute;width:340px;height:340px;border:1px solid #ffffff18;border-radius:50%;right:-130px;bottom:-190px}.cp-vcard-brand{font-size:11px;font-weight:900;letter-spacing:2px}.cp-vcard-chip{width:48px;height:34px;border:1px solid #ffffff70;border-radius:7px;background:linear-gradient(135deg,#f8fafc44,#ffffff12);margin-top:35px}.cp-vcard-number{font-size:27px;letter-spacing:2px;font-weight:800;margin-top:28px}.cp-vcard-meta{display:flex;justify-content:space-between;margin-top:23px;font-size:9px;letter-spacing:1.4px;color:#aebdcb}@media(max-width:520px){.cp-vcard{min-height:220px;padding:21px}.cp-vcard-number{font-size:18px;letter-spacing:1px}}
</style>@endpush
@section('content')
<h1 class="cp-customer-page-title">Virtual Marketplace Card</h1>
<section class="cp-vcard"><div class="cp-vcard-brand">CHACHA PRIME</div><div class="cp-vcard-chip"></div><div class="cp-vcard-number">{{$card ? $card->display_number : 'CARD NOT ISSUED'}}</div><div class="cp-vcard-meta"><span>MARKETPLACE CARD</span><span>{{$card ? 'EXPIRES '.$card->expiry_month.'/'.$card->expiry_year : 'ISSUANCE REQUIRED'}}</span></div></section>
<section class="cp-customer-panel" style="margin-top:15px"><h2 style="margin:0 0 7px;font-size:17px">Card status</h2><p class="cp-customer-muted">{{$card ? 'Your internal marketplace card is available for supported Chacha Prime transactions.' : 'A virtual marketplace card has not been issued to this account yet.'}}</p><p class="cp-customer-muted" style="margin-top:7px">This is an internal closed-loop marketplace card. It is not a Visa or Mastercard bank card.</p></section>
@endsection