@extends('layouts.storefront')
@section('title','Customer Dashboard — Chacha Prime')
@push('styles')
<style>
.cp-cust{min-height:calc(100vh - 104px);background:#f5f7fa;padding:22px}.cp-cust-shell{max-width:1400px;margin:auto;display:grid;grid-template-columns:240px minmax(0,1fr);gap:18px}.cp-cust-side{background:#0b1220;color:#fff;border-radius:18px;padding:15px;position:sticky;top:124px;height:max-content}.cp-cust-logo{width:185px;height:52px;object-fit:contain;object-position:left center}.cp-cust-side h3{margin:9px 0 3px;font-size:18px}.cp-cust-side small{color:#94a3b8;font-size:10px}.cp-cust-nav{display:grid;gap:4px;margin-top:14px}.cp-cust-nav a{color:#cbd5e1;text-decoration:none;padding:10px;border-radius:9px;font-size:12px;font-weight:800}.cp-cust-nav a:hover,.cp-cust-nav a.active{background:#172554;color:#fff}.cp-cust-nav a.active{box-shadow:inset 3px 0 #f59e0b}.cp-cust-main{min-width:0}.cp-cust-hero,.cp-cust-card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 8px 25px #11182708}.cp-cust-hero{padding:24px;display:flex;justify-content:space-between;align-items:center;gap:16px}.cp-cust-ey{font-size:10px;font-weight:900;letter-spacing:1.8px;color:#2563eb}.cp-cust-hero h1{margin:6px 0;font-size:30px}.cp-cust-hero p{margin:0;color:#64748b;font-size:12px}.cp-cust-btn{display:inline-flex;padding:10px 14px;border-radius:10px;background:#0f172a;color:#fff;text-decoration:none;font-size:11px;font-weight:900}.cp-cust-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:15px 0}.cp-cust-stat{background:#fff;border:1px solid #e5e7eb;border-radius:15px;padding:16px;text-decoration:none;color:#111827}.cp-cust-stat span{display:block;color:#64748b;font-size:10px;font-weight:800}.cp-cust-stat strong{display:block;font-size:25px;margin-top:7px}.cp-cust-stat small{color:#94a3b8;font-size:10px}.cp-cust-card{padding:19px}.cp-cust-card h2{margin:0;font-size:18px}.cp-cust-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.cp-cust-action{padding:15px;border:1px solid #e5e7eb;border-radius:13px;text-decoration:none;color:#111827;background:#fafbfc}.cp-cust-action b{font-size:12px}.cp-cust-action span{display:block;color:#64748b;font-size:10px;margin-top:5px}@media(max-width:950px){.cp-cust-shell{grid-template-columns:1fr}.cp-cust-side{position:relative;top:auto}.cp-cust-nav{display:flex;overflow:auto}.cp-cust-nav a{white-space:nowrap}.cp-cust-stats{grid-template-columns:repeat(2,1fr)}.cp-cust-actions{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.cp-cust{padding:12px}.cp-cust-hero{align-items:flex-start;flex-direction:column}.cp-cust-stats,.cp-cust-actions{grid-template-columns:1fr}.cp-cust-side{padding:11px}}
</style>
@endpush
@section('content')
<div class="cp-cust"><div class="cp-cust-shell">
<aside class="cp-cust-side"><a href="{{route('home')}}"><img class="cp-cust-logo" src="{{asset('images/chacha-logo.svg')}}" alt="CHACHA 查查 Prime"></a><h3>Customer Center</h3><small>Personal marketplace account</small><nav class="cp-cust-nav"><a class="active" href="{{route('customer.dashboard')}}">▦ Dashboard</a><a href="{{route('customer.orders')}}">▤ Orders</a><a href="{{route('customer.wishlist')}}">♡ Wishlist</a><a href="{{route('customer.addresses')}}">⌖ Addresses</a><a href="{{route('customer.wallet')}}">▱ Wallet</a><a href="{{route('customer.card')}}">▣ Virtual Card</a><a href="{{route('customer.notifications')}}">◌ Notifications</a><a href="{{route('shop')}}">↗ Shop</a></nav></aside>
<main class="cp-cust-main"><section class="cp-cust-hero"><div><div class="cp-cust-ey">MY CHACHA PRIME</div><h1>Welcome, {{$user->name}}</h1><p>Manage shopping, orders, wallet, virtual card and account services from one place.</p></div><a class="cp-cust-btn" href="{{route('shop')}}">Continue Shopping →</a></section>
<section class="cp-cust-stats">@foreach([['Orders',$stats['orders'],route('customer.orders'),'Your purchases'],['Pending',$stats['pending'],route('customer.orders'),'Needs attention'],['Wishlist',$stats['wishlist'],route('customer.wishlist'),'Saved products'],['Unread alerts',$stats['notifications'],route('customer.notifications'),'Account updates']] as $s)<a class="cp-cust-stat" href="{{$s[2]}}"><span>{{$s[0]}}</span><strong>{{$s[1]}}</strong><small>{{$s[3]}}</small></a>@endforeach</section>
<section class="cp-cust-card"><h2>Quick access</h2><div class="cp-cust-actions"><a class="cp-cust-action" href="{{route('customer.orders')}}"><b>Orders</b><span>Track recent purchases →</span></a><a class="cp-cust-action" href="{{route('customer.addresses')}}"><b>Addresses</b><span>Manage delivery addresses →</span></a><a class="cp-cust-action" href="{{route('customer.wallet')}}"><b>Wallet</b><span>View marketplace balance →</span></a><a class="cp-cust-action" href="{{route('customer.card')}}"><b>Virtual Card</b><span>Open your Chacha card →</span></a></div></section>
</main></div></div>
@endsection