@extends('layouts.customer')
@section('title','My Orders — Chacha Prime')
@push('styles')
<style>
.cp-orders-toolbar{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:15px}.cp-orders-tabs{display:flex;gap:6px;flex-wrap:wrap}.cp-orders-tabs span{padding:8px 11px;border:1px solid #dbe3eb;border-radius:999px;font-size:10px;font-weight:900;color:#475569;background:#fff}.cp-orders-table{background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden}.cp-orders-table table{min-width:760px}.cp-order-no{font-weight:900;color:#0f172a}.cp-order-date{display:block;color:#94a3b8;font-size:10px;margin-top:3px}.cp-order-total{font-weight:900;color:#0f172a}.cp-order-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:#f1f5f9;color:#475569;font-size:9px;font-weight:900;text-transform:uppercase}.cp-order-status.delivered,.cp-order-status.completed{background:#ecfdf5;color:#047857}.cp-order-status.cancelled,.cp-order-status.failed{background:#fef2f2;color:#b91c1c}.cp-order-actions{display:flex;gap:6px;flex-wrap:wrap}.cp-order-actions a{padding:8px 10px;border:1px solid #dbe3eb;border-radius:8px;text-decoration:none;color:#0f172a;font-size:10px;font-weight:900}.cp-order-actions a.primary{background:#0f172a;color:#fff;border-color:#0f172a}
</style>
@endpush
<h1 class="cp-customer-page-title">My Orders</h1>
<div class="cp-orders-toolbar"><div><div style="font-size:11px;color:#64748b">Your complete purchase history, fulfillment and payment status.</div></div><a class="cp-premium-btn primary" href="{{route('shop')}}">Continue shopping</a></div>
@if(session('success'))<div class="cp-customer-panel" style="margin-bottom:14px;color:#047857">{{session('success')}}</div>@endif
<section class="cp-orders-table"><div class="cp-orders-tabs" style="padding:14px;border-bottom:1px solid #edf2f7"><span>All orders</span><span>Recent purchases</span><span>Track delivery</span><span>Returns</span></div><div class="cp-customer-table"><table><thead><tr><th>Order details</th><th>Total</th><th>Payment</th><th>Fulfillment</th><th>Actions</th></tr></thead><tbody>
@forelse($orders as $o)
<tr><td><span class="cp-order-no">#{{$o->order_number}}</span><span class="cp-order-date">{{IlluminateSupportCarbon::parse($o->created_at)->format('d M Y, H:i')}}</span></td><td><span class="cp-order-total">{{$o->grand_total}} {{$o->currency}}</span></td><td><span class="cp-order-status {{strtolower($o->payment_status)}}">{{$o->payment_status}}</span></td><td><span class="cp-order-status {{strtolower($o->fulfillment_status)}}">{{$o->fulfillment_status}}</span></td><td><div class="cp-order-actions"><a class="primary" href="{{route('customer.order.detail',$o->id)}}">View order</a><a href="{{route('customer.invoice',$o->id)}}">Invoice</a></div></td></tr>
@empty<tr><td colspan="5"><div style="padding:35px;text-align:center;color:#64748b">No orders yet. Explore the marketplace to place your first order.</div></td></tr>@endforelse
</tbody></table></div></section><div style="margin-top:14px">{{$orders->links()}}</div>
@endsection