@extends('layouts.customer')
@section('title','Order '.$order->order_number.' — Chacha Prime')
@push('styles')
<style>
.cp-order-hero{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:24px;border-radius:18px;background:linear-gradient(135deg,#0b1220,#172a43);color:#fff}.cp-order-hero span{display:block;font-size:9px;letter-spacing:1.5px;color:#94a3b8}.cp-order-hero strong{display:block;font-size:26px;margin:5px 0}.cp-order-hero small{color:#b8c5d4;font-size:11px}.cp-order-track{display:grid;grid-template-columns:repeat(4,1fr);background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:22px;margin:15px 0}.cp-order-track div{position:relative;text-align:center;font-size:10px;font-weight:900;color:#94a3b8}.cp-order-track div:not(:last-child):after{content:"";position:absolute;top:6px;left:50%;width:100%;height:2px;background:#e2e8f0}.cp-order-track i{position:relative;z-index:1;display:block;width:14px;height:14px;margin:0 auto 8px;border:3px solid #cbd5e1;background:#fff;border-radius:50%}.cp-order-track .done{color:#334155}.cp-order-track .done i{border-color:#f59e0b;background:#f59e0b}.cp-order-track .done:not(:last-child):after{background:#f59e0b}.cp-order-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.7fr);gap:15px}.cp-order-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:19px}.cp-order-card h2{font-size:16px;margin:0 0 13px}.cp-order-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;padding:14px 0;border-top:1px solid #edf2f7}.cp-order-item strong{font-size:12px}.cp-order-item small{display:block;color:#64748b;font-size:10px;margin-top:4px}.cp-order-item b{font-size:12px}.cp-order-line{display:flex;justify-content:space-between;gap:15px;padding:8px 0;font-size:11px;color:#475569}.cp-order-line.total{border-top:1px solid #e2e8f0;margin-top:6px;padding-top:13px;color:#0f172a;font-weight:900;font-size:14px}.cp-return-box{margin-top:15px;background:#fffaf0;border:1px solid #f6d79b;border-radius:14px;padding:16px}.cp-return-box h3{margin:0 0 6px;font-size:14px}.cp-return-box p{margin:0 0 13px;color:#64748b;font-size:10px;line-height:1.6}.cp-return-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cp-return-form label{font-size:10px;font-weight:800;color:#475569}.cp-return-form input,.cp-return-form select,.cp-return-form textarea{width:100%;margin-top:5px;padding:10px;border:1px solid #d3dce6;border-radius:8px;font:inherit;font-size:11px;box-sizing:border-box}.cp-return-form textarea{min-height:72px;resize:vertical}.cp-return-form .full{grid-column:1/-1}.cp-return-form button{grid-column:1/-1;justify-self:start}.cp-shipment{padding:12px;border:1px solid #e5eaf0;border-radius:11px;margin-top:9px}.cp-shipment strong{font-size:11px}.cp-shipment span{display:block;color:#64748b;font-size:10px;margin-top:4px}
@media(max-width:900px){.cp-order-layout{grid-template-columns:1fr}}@media(max-width:650px){.cp-order-hero{align-items:flex-start;flex-direction:column}.cp-order-track{grid-template-columns:1fr 1fr;gap:20px}.cp-return-form{grid-template-columns:1fr}.cp-return-form .full,.cp-return-form button{grid-column:1}}
</style>
@endpush
<h1 class="cp-customer-page-title">Order #{{$order->order_number}}</h1>
<section class="cp-order-hero"><div><span>ORDER STATUS</span><strong>{{ucfirst($order->status)}}</strong><small>Payment: {{ucfirst($order->payment_status)}} · Fulfillment: {{ucfirst($order->fulfillment_status)}}</small></div><a class="cp-premium-btn" href="{{route('customer.invoice',$order->id)}}">View invoice</a></section>
<section class="cp-order-track"><div class="done"><i></i><span>Order placed</span></div><div class="{{$order->status!=='pending'?'done':''}}"><i></i><span>Confirmed</span></div><div class="{{$order->fulfillment_status!=='pending'?'done':''}}"><i></i><span>Packed and shipped</span></div><div class="{{$order->fulfillment_status==='delivered'?'done':''}}"><i></i><span>Delivered</span></div></section>
<div class="cp-order-layout"><section class="cp-order-card"><h2>Items in this order</h2>@foreach($items as $i)<div class="cp-order-item"><div><strong>{{$i->product_name}}</strong><small>Quantity: {{$i->quantity}} · Seller: {{optional(DB::table('vendors')->where('id',$i->vendor_id)->first())->business_name ?? 'Marketplace seller'}}</small></div><b>{{$i->subtotal}} {{$i->currency ?? $order->currency}}</b></div>@endforeach
@if($order->fulfillment_status==='delivered')<div class="cp-return-box"><h3>Return this order</h3><p>Return requests are accepted within 7 days after delivery. Clear product photos and at least one video are required for condition and originality review.</p>@foreach($items as $i)<form class="cp-return-form" method="POST" enctype="multipart/form-data" action="{{route('customer.returns.request',$order->id)}}">@csrf<input type="hidden" name="order_item_id" value="{{$i->id}}"><label>Return reason<select name="reason" required><option value="">Select a reason</option><option>Damaged item</option><option>Wrong item</option><option>Not as described</option><option>Changed my mind</option><option>Other</option></select></label><label>Issue details<input name="details" required placeholder="Describe the issue"></label><label>Product photos<input type="file" name="evidence_images[]" accept="image/jpeg,image/png,image/webp" multiple required></label><label>Product video<input type="file" name="evidence_videos[]" accept="video/mp4,video/webm,video/quicktime" multiple required></label><button class="cp-premium-btn primary" type="submit">Submit return request</button></form>@endforeach</div>@endif</section>
<aside><section class="cp-order-card"><h2>Payment summary</h2><div class="cp-order-line"><span>Subtotal</span><b>{{$order->subtotal}} {{$order->currency}}</b></div><div class="cp-order-line"><span>Shipping</span><b>{{$order->shipping_total ?? '0.00'}} {{$order->currency}}</b></div><div class="cp-order-line"><span>Tax</span><b>{{$order->tax_total ?? '0.00'}} {{$order->currency}}</b></div><div class="cp-order-line total"><span>Total</span><b>{{$order->grand_total}} {{$order->currency}}</b></div></section><section class="cp-order-card" style="margin-top:15px"><h2>Shipment tracking</h2>@forelse($shipments as $s)<div class="cp-shipment"><strong>{{$s->tracking_number ?: 'Tracking pending'}}</strong><span>Status: {{ucfirst($s->status)}}</span></div>@empty<p class="cp-customer-muted">Shipment has not been created yet.</p>@endforelse</section></aside></div>
@endsection