@extends('layouts.customer')
@section('title','Returns & Refunds — Chacha Prime')
@push('styles')
<style>.cp-returns-note{background:#fffaf0;border:1px solid #f6d79b;border-radius:14px;padding:16px;margin-bottom:15px}.cp-returns-note strong{display:block;font-size:13px}.cp-returns-note span{display:block;color:#64748b;font-size:10px;line-height:1.6;margin-top:5px}.cp-return-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:#f1f5f9;color:#475569;font-size:9px;font-weight:900;text-transform:uppercase}.cp-return-status.approved,.cp-return-status.refunded,.cp-return-status.completed{background:#ecfdf5;color:#047857}.cp-return-status.rejected,.cp-return-status.cancelled{background:#fef2f2;color:#b91c1c}</style>
@endpush
<h1 class="cp-customer-page-title">Returns & Refunds</h1>
<div class="cp-returns-note"><strong>7-day return window</strong><span>Once an order is marked delivered, a return request must be submitted within 7 days. Evidence photos and at least one product video are required for review.</span></div>
@if(session('success'))<div class="cp-customer-panel" style="margin-bottom:14px;color:#047857">{{session('success')}}</div>@endif
<section class="cp-premium-table"><div class="cp-customer-table"><table><thead><tr><th>Order</th><th>Seller</th><th>Reason</th><th>Refund</th><th>Return deadline</th><th>Status</th></tr></thead><tbody>@forelse($returns as $r)<tr><td><strong>#{{$r->order_number}}</strong></td><td>{{e($r->business_name)}}</td><td>{{e($r->reason)}}</td><td><strong>{{$r->currency}} {{number_format((float)$r->refund_amount,2)}}</strong></td><td>{{$r->return_deadline_at ? IlluminateSupportCarbon::parse($r->return_deadline_at)->format('d M Y, H:i') : 'Not set'}}</td><td><span class="cp-return-status {{strtolower($r->status)}}">{{$r->status}}</span></td></tr>@empty<tr><td colspan="6"><div class="cp-customer-muted" style="padding:35px;text-align:center">No return requests yet.</div></td></tr>@endforelse</tbody></table></div></section>
<div style="margin-top:14px">{{$returns->links()}}</div>
@endsection