<?php
namespace App\Http\Controllers;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class StorefrontController extends Controller {
 public function home(){return view('storefront.home',['featured'=>Product::where('status','published')->latest()->limit(8)->get()]);}
 public function shop(Request $request){$q=$request->get('q');$products=Product::where('status','published')->when($q,fn($x)=>$x->where(fn($y)=>$y->where('name','like',"%$q%")->orWhere('description','like',"%$q%")))->latest()->paginate(24)->withQueryString();return view('storefront.shop',compact('products','q'));}
 public function product(int $id){$product=Product::where('status','published')->findOrFail($id);return view('storefront.product',compact('product'));}
 public function cart(Request $request){$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get();$total=$products->sum(fn($p)=>$p->retail_price*($cart[$p->id]??0));return view('storefront.cart',compact('products','cart','total'));}
 public function addToCart(Request $request,int $id){$p=Product::where('status','published')->findOrFail($id);$qty=max(1,(int)$request->input('quantity',1));abort_if($p->stock_status==='out_of_stock'||$p->stock<$qty,422,'Insufficient stock.');$cart=$request->session()->get('cart',[]);$newQty=($cart[$id]??0)+$qty;abort_if($p->stock<$newQty,422,'Requested quantity exceeds stock.');$cart[$id]=$newQty;$request->session()->put('cart',$cart);return back()->with('success',$p->name.' added to cart.');}
 public function removeFromCart(Request $request,int $id){$cart=$request->session()->get('cart',[]);unset($cart[$id]);$request->session()->put('cart',$cart);return back();}
 public function checkout(Request $request){$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get();abort_if($products->isEmpty(),404,'Cart is empty');$methods=DB::table('payment_methods')->where('enabled',1)->get();$addresses=DB::table('addresses')->where('user_id',$request->user()->id)->orderByDesc('is_default')->get();$total=$products->sum(fn($p)=>$p->retail_price*($cart[$p->id]??0));return view('storefront.checkout',compact('products','cart','total','methods','addresses'));}
 public function placeOrder(Request $request){$data=$request->validate(['payment_method_id'=>'required|exists:payment_methods,id','address_id'=>'required|exists:addresses,id']);$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get()->keyBy('id');abort_if($products->isEmpty(),422,'Cart is empty.');abort_unless(DB::table('addresses')->where('id',$data['address_id'])->where('user_id',$request->user()->id)->exists(),403);foreach($cart as $id=>$qty){abort_if(!$products->has($id)||$products[$id]->stock<$qty||$products[$id]->stock_status==='out_of_stock',422,'One or more products are unavailable.');}
 $address=DB::table('addresses')->where('id',$data['address_id'])->first();$groups=$products->groupBy('vendor_id');$orderIds=DB::transaction(function()use($groups,$cart,$address,$data,$request){$ids=[];foreach($groups as $vendorId=>$items){$subtotal=$items->sum(fn($p)=>$p->retail_price*$cart[$p->id]);$orderId=DB::table('orders')->insertGetId(['user_id'=>$request->user()->id,'order_number'=>'CP-'.strtoupper(bin2hex(random_bytes(5))),'status'=>'pending','payment_status'=>'pending','fulfillment_status'=>'unfulfilled','currency'=>'USD','subtotal'=>$subtotal,'grand_total'=>$subtotal,'shipping_address'=>json_encode($address),'billing_address'=>json_encode($address),'created_at'=>now(),'updated_at'=>now()]);foreach($items as $p){$qty=$cart[$p->id];DB::table('order_items')->insert(['order_id'=>$orderId,'vendor_id'=>$p->vendor_id,'product_id'=>$p->id,'product_name'=>$p->name,'sku'=>$p->sku,'quantity'=>$qty,'unit_price'=>$p->retail_price,'subtotal'=>$p->retail_price*$qty,'created_at'=>now()]);DB::table('products')->where('id',$p->id)->decrement('stock',$qty);DB::table('products')->where('id',$p->id)->update(['stock_status'=>DB::raw("CASE WHEN stock <= 0 THEN 'out_of_stock' ELSE 'in_stock' END")]);}DB::table('payments')->insert(['order_id'=>$orderId,'user_id'=>$request->user()->id,'method_id'=>$data['payment_method_id'],'amount'=>$subtotal,'currency'=>'USD','status'=>'pending','created_at'=>now(),'updated_at'=>now()]);$ids[]=$orderId;}return $ids;});$request->session()->forget('cart');return redirect()->route('customer.orders')->with('success','Order(s) placed successfully: #'.implode(', #',$orderIds));}
 public function customerDashboard(Request $request){$user=$request->user();$stats=['orders'=>DB::table('orders')->where('user_id',$user->id)->count(),'pending'=>DB::table('orders')->where('user_id',$user->id)->whereIn('status',['pending','processing'])->count(),'wishlist'=>DB::table('wishlists')->where('user_id',$user->id)->count(),'notifications'=>DB::table('notifications')->where('user_id',$user->id)->whereNull('read_at')->count()];return view('customer.dashboard',compact('user','stats'));}
 public function customerOrders(Request $request){$orders=DB::table('orders')->where('user_id',$request->user()->id)->latest()->paginate(20);return view('customer.orders',compact('orders'));}
 public function orderDetail(Request $request,int $id){$order=DB::table('orders')->where('id',$id)->where('user_id',$request->user()->id)->firstOrFail();$items=DB::table('order_items')->where('order_id',$id)->get();$shipments=DB::table('shipments')->where('order_id',$id)->latest()->get();return view('customer.order-detail',compact('order','items','shipments'));}
 public function wishlist(Request $request){$items=DB::table('wishlists')->join('products','products.id','=','wishlists.product_id')->where('wishlists.user_id',$request->user()->id)->select('wishlists.*','products.name','products.retail_price','products.currency')->latest('wishlists.created_at')->get();return view('customer.wishlist',compact('items'));}
 public function addWishlist(Request $request,int $id){Product::where('status','published')->findOrFail($id);DB::table('wishlists')->updateOrInsert(['user_id'=>$request->user()->id,'product_id'=>$id],['created_at'=>now()]);return back()->with('success','Added to wishlist.');}
 public function removeWishlist(Request $request,int $id){DB::table('wishlists')->where('user_id',$request->user()->id)->where('product_id',$id)->delete();return back()->with('success','Removed from wishlist.');}
 public function addresses(Request $request){$addresses=DB::table('addresses')->where('user_id',$request->user()->id)->orderByDesc('is_default')->get();return view('customer.addresses',compact('addresses'));}
 public function storeAddress(Request $request){$data=$request->validate(['label'=>'nullable|string|max:60','recipient_name'=>'required|string|max:120','phone'=>'nullable|string|max:40','country'=>'required|string|max:100','state'=>'nullable|string|max:120','city'=>'nullable|string|max:120','postal_code'=>'nullable|string|max:30','address_line1'=>'required|string|max:255','address_line2'=>'nullable|string|max:255','is_default'=>'nullable|boolean']);if(!empty($data['is_default']))DB::table('addresses')->where('user_id',$request->user()->id)->update(['is_default'=>0]);$data['user_id']=$request->user()->id;$data['is_default']=(int)($data['is_default']??0);$data['created_at']=now();$data['updated_at']=now();DB::table('addresses')->insert($data);return back()->with('success','Address saved.');}
 public function wallet(Request $request){$wallet=DB::table('wallets')->where('user_id',$request->user()->id)->first();$transactions=$wallet?DB::table('wallet_transactions')->where('wallet_id',$wallet->id)->latest()->limit(30)->get():collect();return view('customer.wallet',compact('wallet','transactions'));}
 public function card(Request $request){$card=DB::table('virtual_cards')->where('user_id',$request->user()->id)->first();return view('customer.card',compact('card'));}
 public function notifications(Request $request){$notifications=DB::table('notifications')->where('user_id',$request->user()->id)->latest()->paginate(30);DB::table('notifications')->where('user_id',$request->user()->id)->whereNull('read_at')->update(['read_at'=>now()]);return view('customer.notifications',compact('notifications'));}
}