<?php
namespace App\Http\Controllers;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class StorefrontController extends Controller {
 public function home(){return view('storefront.home',['featured'=>Product::where('status','published')->latest()->limit(8)->get()]);}
 public function shop(Request $request){$q=$request->get('q');$products=Product::where('status','published')->when($q,fn($x)=>$x->where(fn($y)=>$y->where('name','like',"%$q%")->orWhere('description','like',"%$q%")))->latest()->paginate(24)->withQueryString();return view('storefront.shop',compact('products','q'));}
 public function product(int $id){$product=Product::where('status','published')->findOrFail($id);return view('storefront.product',compact('product'));}
 public function cart(Request $request){$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get();$total=$products->sum(fn($p)=>$p->price*($cart[$p->id]??0));return view('storefront.cart',compact('products','cart','total'));}
 public function addToCart(Request $request,int $id){$p=Product::where('status','published')->findOrFail($id);$cart=$request->session()->get('cart',[]);$cart[$id]=($cart[$id]??0)+max(1,(int)$request->input('quantity',1));$request->session()->put('cart',$cart);return back()->with('success',$p->name.' added to cart.');}
 public function removeFromCart(Request $request,int $id){$cart=$request->session()->get('cart',[]);unset($cart[$id]);$request->session()->put('cart',$cart);return back();}
 public function checkout(Request $request){abort_unless($request->user(),403);$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get();abort_if($products->isEmpty(),404,'Cart is empty');$total=$products->sum(fn($p)=>$p->price*($cart[$p->id]??0));$methods=DB::table('payment_methods')->where('enabled',1)->get();return view('storefront.checkout',compact('products','cart','total','methods'));}
 public function placeOrder(Request $request){abort_unless($request->user(),403);$cart=$request->session()->get('cart',[]);$products=Product::whereIn('id',array_keys($cart))->get();abort_if($products->isEmpty(),404,'Cart is empty');$data=$request->validate(['payment_method_id'=>'required|exists:payment_methods,id']);$total=$products->sum(fn($p)=>$p->price*($cart[$p->id]??0));$orderId=DB::table('orders')->insertGetId(['user_id'=>$request->user()->id,'status'=>'pending','payment_status'=>'pending','fulfillment_status'=>'pending','total_amount'=>$total,'currency'=>'USD','created_at'=>now(),'updated_at'=>now()]);foreach($products as $p){DB::table('order_items')->insert(['order_id'=>$orderId,'product_id'=>$p->id,'vendor_id'=>$p->vendor_id,'quantity'=>$cart[$p->id],'unit_price'=>$p->price,'total_price'=>$p->price*$cart[$p->id],'created_at'=>now(),'updated_at'=>now()]);}DB::table('payments')->insert(['order_id'=>$orderId,'user_id'=>$request->user()->id,'payment_method_id'=>$data['payment_method_id'],'amount'=>$total,'currency'=>'USD','status'=>'pending','created_at'=>now(),'updated_at'=>now()]);$request->session()->forget('cart');return redirect()->route('customer.orders')->with('success','Order placed successfully.');}
 public function customerOrders(Request $request){$orders=DB::table('orders')->where('user_id',$request->user()->id)->latest()->paginate(20);return view('customer.orders',compact('orders'));}
 public function wishlist(Request $request){$items=DB::table('wishlists')->where('user_id',$request->user()->id)->latest()->get();return view('customer.wishlist',compact('items'));}
 public function addWishlist(Request $request,int $id){Product::where('status','published')->findOrFail($id);DB::table('wishlists')->updateOrInsert(['user_id'=>$request->user()->id,'product_id'=>$id],['created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Added to wishlist.');}
}