<?php
namespace App\Http\Controllers;
use App\Models\Product;
use App\Models\Vendor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class VendorController extends Controller {
 public function dashboard(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$p=Product::where('vendor_id',$vendor->id);return view('vendor.dashboard',['vendor'=>$vendor,'stats'=>['products'=>(clone $p)->count(),'published'=>(clone $p)->where('status','published')->count(),'pending'=>(clone $p)->where('status','pending')->count(),'orders'=>DB::table('orders')->where('vendor_id',$vendor->id)->count(),'sales'=>DB::table('orders')->where('vendor_id',$vendor->id)->whereIn('status',['paid','processing','shipped','delivered'])->sum('total_amount'),'reviews'=>DB::table('reviews')->where('vendor_id',$vendor->id)->count(),'low_stock'=>(clone $p)->where('stock_quantity','<=',10)->count()],'recentProducts'=>(clone $p)->latest()->limit(8)->get()]);}
 public function products(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();return view('vendor.products',['vendor'=>$vendor,'products'=>Product::where('vendor_id',$vendor->id)->latest()->paginate(15),'categories'=>DB::table('categories')->where('status',1)->orderBy('name')->get()]);}
 public function storeProduct(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$d=$request->validate(['name'=>'required|string|max:255','category_id'=>'required|exists:categories,id','description'=>'nullable|string','price'=>'required|numeric|min:0','stock_quantity'=>'required|integer|min:0','sku'=>'nullable|string|max:100']);$d['vendor_id']=$vendor->id;$d['slug']=Str::slug($d['name']).'-'.Str::lower(Str::random(6));$d['status']='pending';$d['stock_status']=$d['stock_quantity']>0?'in_stock':'out_of_stock';Product::create($d);return back()->with('success','Product submitted for admin approval.');}
 public function updateProduct(Request $request,int $id){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$p=Product::where('vendor_id',$vendor->id)->findOrFail($id);$d=$request->validate(['name'=>'required|string|max:255','category_id'=>'required|exists:categories,id','description'=>'nullable|string','price'=>'required|numeric|min:0','stock_quantity'=>'required|integer|min:0','sku'=>'nullable|string|max:100']);$d['stock_status']=$d['stock_quantity']>0?'in_stock':'out_of_stock';$p->update($d);return back()->with('success','Product updated.');}
 public function editProduct(Request $request,int $id){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$product=Product::where('vendor_id',$vendor->id)->findOrFail($id);$categories=DB::table('categories')->where('status',1)->orderBy('name')->get();return view('vendor.product-edit',compact('vendor','product','categories'));}
 public function deleteProduct(Request $request,int $id){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$product=Product::where('vendor_id',$vendor->id)->findOrFail($id);$product->delete();return back()->with('success','Product deleted.');}
 public function pricing(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$products=Product::where('vendor_id',$vendor->id)->latest()->paginate(20);$tiers=DB::table('pricing_tiers')->where('active',1)->get();return view('vendor.pricing',compact('vendor','products','tiers'));}
 public function inventory(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$products=Product::where('vendor_id',$vendor->id)->orderBy('stock_quantity')->paginate(25);return view('vendor.inventory',compact('vendor','products'));}
 public function analytics(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$orders=DB::table('orders')->where('vendor_id',$vendor->id);return view('vendor.analytics',['vendor'=>$vendor,'stats'=>['orders'=>(clone $orders)->count(),'sales'=>(clone $orders)->whereIn('status',['paid','processing','shipped','delivered'])->sum('total_amount'),'pending'=>(clone $orders)->where('status','pending')->count(),'delivered'=>(clone $orders)->where('status','delivered')->count()]]);}
 public function orders(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();return view('vendor.orders',['vendor'=>$vendor,'orders'=>DB::table('orders')->where('vendor_id',$vendor->id)->latest()->paginate(20)]);}
 public function updateOrder(Request $request,int $id){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$request->validate(['status'=>'required|in:pending,paid,processing,shipped,delivered,cancelled,refunded']);$n=DB::table('orders')->where('id',$id)->where('vendor_id',$vendor->id)->update(['status'=>$request->status,'updated_at'=>now()]);abort_unless($n,404);return back()->with('success','Order status updated.');}
 public function wallet(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();$wallet=DB::table('wallets')->where('user_id',$request->user()->id)->first();return view('vendor.wallet',compact('vendor','wallet'));}
 public function reviews(Request $request){$vendor=Vendor::where('user_id',$request->user()->id)->firstOrFail();return view('vendor.reviews',['vendor'=>$vendor,'reviews'=>DB::table('reviews')->where('vendor_id',$vendor->id)->latest()->paginate(20)]);}
}