@php $cart=session('cart',[]); $cartCount=collect($cart)->sum(fn($q)=>(int)$q); $user=auth()->user(); $role=$user?->role; @endphp
<header class="cp-header">
<div class="cp-topbar"><div class="cp-top-inner">
<button class="cp-icon-btn cp-mobile-menu-btn" type="button" data-cp-open-drawer aria-label="Open categories"><span class="cp-hamburger-icon" aria-hidden="true"></span></button>
<a class="cp-logo" href="{{route('home')}}"><img src="{{asset('images/chacha-logo.svg')}}" alt="CHACHA 查查 Prime"></a>
<a class="cp-deliver" href="{{route("marketplace.country.selector")}}"><span class="cp-pin-icon" aria-hidden="true"></span><span><small>Deliver to</small><strong>{{$marketplaceCountry?->flag}} {{$marketplaceCountry?->name ?? "Choose country"}}</strong></span></a>
@include('partials.search-bar')
<div class="cp-header-actions">
<a class="cp-lang" href="{{route("marketplace.country.selector")}}" style="text-decoration:none"><span class="cp-globe-icon" aria-hidden="true"></span> {{$marketplaceCountry?->currency_code ?? "USD"}} <span class="cp-chevron">⌄</span></a>
<div class="cp-account-wrap"><button class="cp-account" type="button" data-cp-account><small>Hello, {{$user?->name ? \Illuminate\Support\Str::limit($user->name,16) : 'sign in'}}</small><strong>Account &amp; Lists <span class="cp-chevron">⌄</span></strong></button>@include('partials.account-dropdown')</div>
<a class="cp-returns" href="{{$user?route('customer.orders'):route('auth.login')}}"><small>Returns</small><strong>&amp; Orders</strong></a>
<div class="cp-cart-wrap"><a class="cp-cart" href="{{route('cart')}}" data-cp-cart><span class="cp-cart-icon" aria-hidden="true"></span><b>{{$cartCount}}</b><strong>Cart</strong></a><div class="cp-mini-cart" data-cp-cart-menu><div class="cp-mini-cart-head">Cart <b>{{$cartCount}} item{{ $cartCount===1 ? "" : "s" }}</b></div>@if($cartCount)<div class="cp-mini-cart-items">@foreach(session("cart",[]) as $pid=>$qty)<div class="cp-mini-cart-row"><span>Product #{{$pid}}</span><b>×{{$qty}}</b></div>@endforeach</div><a class="cp-mini-cart-btn" href="{{route("cart")}}">View cart &amp; checkout</a>@else<div class="cp-mini-cart-empty">Your cart is empty.</div><a class="cp-mini-cart-btn" href="{{route("shop")}}">Start shopping</a>@endif</div></div>
</div></div></div>
<nav class="cp-subbar"><div class="cp-sub-inner">
<button class="cp-nav-link cp-all-link" type="button" data-cp-open-drawer><span class="cp-hamburger-icon" aria-hidden="true"></span> All</button>
<a class="cp-nav-link" href="{{route('live')}}"><span class="cp-live-dot"></span> Live</a>
<a class="cp-nav-link" href="{{route('group-buying')}}">Group Buying</a><a class="cp-nav-link" href="{{route('shop')}}?deals=1">Coupons &amp; Deals</a>
<a class="cp-nav-link" href="{{$user?route('customer.support'):route('ai.assistant')}}">Customer Service</a><a class="cp-nav-link" href="{{route('ai.assistant')}}">AI Support</a><a class="cp-nav-link" href="{{route('shop')}}?deals=1">Today's Deals</a><a class="cp-nav-link" href="{{route('shop')}}?deals=1">Flash Deals</a><a class="cp-nav-link" href="{{route('shop')}}">B2B</a><a class="cp-nav-link" href="{{route('shop')}}">B2C</a><a class="cp-nav-link" href="{{$role==='vendor'?route('vendor.dashboard'):route('vendor.register')}}">Sell with us</a><span class="cp-promo">Premium marketplace • B2B &amp; B2C</span>
</div></nav>
<style>
.cp-cart-wrap{position:relative}.cp-mini-cart{display:none;position:absolute;right:0;top:calc(100% + 8px);width:300px;background:#fff;color:#111827;border:1px solid #dbe1e8;border-radius:12px;box-shadow:0 20px 45px #0f172a22;padding:12px;z-index:100}.cp-cart-wrap:hover .cp-mini-cart{display:block}.cp-mini-cart-head{display:flex;justify-content:space-between;font-weight:900;font-size:12px;padding-bottom:9px;border-bottom:1px solid #eef0f3}.cp-mini-cart-head b{color:#64748b;font-size:10px}.cp-mini-cart-row{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #f1f5f9;font-size:10px}.cp-mini-cart-btn{display:block;text-align:center;margin-top:10px;background:#0f172a;color:#fff!important;text-decoration:none;padding:10px;border-radius:8px;font-size:10px;font-weight:900}.cp-mini-cart-empty{padding:18px 5px;text-align:center;color:#64748b;font-size:11px}
.cp-hamburger-icon{display:inline-block;width:17px;height:12px;border-top:2px solid currentColor;border-bottom:2px solid currentColor;position:relative;vertical-align:-1px}.cp-hamburger-icon:after{content:"";position:absolute;left:0;right:0;top:4px;border-top:2px solid currentColor}.cp-pin-icon{width:11px;height:11px;border:2px solid currentColor;border-radius:50% 50% 50% 0;display:inline-block;transform:rotate(-45deg);margin:0 3px 2px 1px}.cp-globe-icon{display:inline-block;width:14px;height:14px;border:1.5px solid currentColor;border-radius:50%;position:relative;vertical-align:-2px;margin-right:3px}.cp-globe-icon:before{content:"";position:absolute;left:5px;top:0;bottom:0;border-left:1px solid currentColor}.cp-globe-icon:after{content:"";position:absolute;left:2px;right:2px;top:5px;border-top:1px solid currentColor}.cp-cart-icon{display:inline-block;width:24px;height:17px;border:2px solid currentColor;border-top:0;transform:skew(-8deg);position:relative;margin-bottom:4px}.cp-cart-icon:before{content:"";position:absolute;left:-5px;top:-6px;width:8px;border-top:2px solid currentColor}.cp-cart-icon:after{content:"•  •";position:absolute;left:2px;top:11px;font-size:14px;letter-spacing:6px;transform:skew(8deg)}
.cp-live-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#ff526b;vertical-align:1px;box-shadow:0 0 0 3px #ff526b22}
</style>
<div class="cp-support-float" data-cp-support-float>
<a class="cp-support-float-main" href="{{route('ai.assistant')}}" aria-label="Open AI Support"><span class="cp-support-spark">✦</span><span><b>AI Support</b><small>Help with orders & products</small></span></a>
<div class="cp-support-float-actions"><a href="{{route('ai.assistant')}}">AI Chat</a><a href="mailto:support@chachaprime.com">Email</a><a href="https://wa.me/" target="_blank" rel="noopener">WhatsApp</a></div>
</div></header>
@include('partials.mega-menu')