@extends('layouts.storefront')
@section('title','Shopping Cart — CHACHA 查查')
@push('styles')
<style>
.cp-cart-page{background:#eaeded;min-height:calc(100vh - 104px);padding:20px}.cp-cart-shell{max-width:1400px;margin:auto}.cp-cart-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:14px}.cp-cart-head h1{font-size:28px;margin:0}.cp-cart-layout{display:grid;grid-template-columns:1fr 330px;gap:16px}.cp-cart-items,.cp-cart-summary{background:#fff;border-radius:8px;padding:20px}.cp-cart-item{display:grid;grid-template-columns:115px 1fr auto;gap:18px;padding:18px 0;border-bottom:1px solid #e5e7eb}.cp-cart-item:first-child{padding-top:0}.cp-cart-img{width:115px;height:115px;background:#f7f8fa;display:grid;place-items:center}.cp-cart-img img{max-width:100%;max-height:100%;object-fit:contain}.cp-cart-item h3{font-size:15px;margin:0 0 7px}.cp-cart-meta{font-size:11px;color:#64748b;line-height:1.7}.cp-cart-price{font-size:17px;font-weight:900}.cp-cart-summary{height:max-content;position:sticky;top:118px}.cp-summary-row{display:flex;justify-content:space-between;padding:8px 0;font-size:12px}.cp-summary-total{display:flex;justify-content:space-between;padding:15px 0;border-top:1px solid #ddd;font-size:20px;font-weight:900}.cp-checkout-btn{display:block;text-align:center;background:#ffd814;color:#111827;text-decoration:none;border:1px solid #f0b800;border-radius:7px;padding:12px;font-weight:900}.cp-remove{margin-top:10px;border:0;background:none;color:#007185;font-size:11px;cursor:pointer;padding:0}@media(max-width:850px){.cp-cart-layout{grid-template-columns:1fr}.cp-cart-summary{position:static}}@media(max-width:520px){.cp-cart-page{padding:10px}.cp-cart-items,.cp-cart-summary{padding:14px}.cp-cart-item{grid-template-columns:80px 1fr;gap:10px}.cp-cart-img{width:80px;height:80px}.cp-cart-price{grid-column:2}}
</style>
@endpush
@section('content')
<div class="cp-cart-page"><div class="cp-cart-shell"><div class="cp-cart-head"><div><div style="font-size:10px;color:#c45500;font-weight:900;letter-spacing:1px">CHACHA 查查</div><h1>Shopping Cart</h1></div><span style="font-size:11px;color:#64748b">{{$products->count()}} product types</span></div>@if(session('success'))<div class="notice">{{session('success')}}</div>@endif
<div class="cp-cart-layout"><section class="cp-cart-items">@forelse($products as $p)<div class="cp-cart-item"><div class="cp-cart-img">@if($p->images->count())<img src="{{asset('storage/'.$p->images->first()->path)}}" alt="{{e($p->name)}}">@endif</div><div><h3><a href="{{route('product',$p->id)}}" style="color:#111827;text-decoration:none">{{$p->name}}</a></h3><div class="cp-cart-meta">Sold by {{$p->vendor?->business_name ?? 'Marketplace Seller'}}<br>Quantity: {{$cart[$p->id]}}<br>{{$p->stock>0?'In Stock':'Currently unavailable'}}</div><form method="POST" action="{{route('cart.remove',$p->id)}}">@csrf<button class="cp-remove">Delete</button></form></div><div class="cp-cart-price">{{$p->currency}} {{number_format($prices[$p->id]*$cart[$p->id],2)}}</div></div>@empty<p>Your cart is empty. <a href="{{route('shop')}}">Continue shopping</a>.</p>@endforelse</section><aside class="cp-cart-summary"><h2 style="font-size:17px;margin-top:0">Order summary</h2><div class="cp-summary-row"><span>Items</span><strong>{{$products->count()}}</strong></div><div class="cp-summary-total"><span>Subtotal</span><span>{{number_format($total,2)}} USD</span></div>@if($products->count())<a class="cp-checkout-btn" href="{{route('checkout')}}">Proceed to checkout</a><p style="font-size:10px;color:#64748b;line-height:1.6">Secure checkout • Multiple payment methods • Buyer protection</p>@endif</aside></div></div></div>
@endsection