@extends('layouts.storefront')
@section('title','Secure Checkout — CHACHA 查查')
@push('styles')
<style>
.cp-checkout{background:#eaeded;min-height:calc(100vh - 104px);padding:20px}.cp-checkout-shell{max-width:1280px;margin:auto}.cp-checkout-top{background:#fff;padding:18px 22px;border-radius:8px;margin-bottom:14px}.cp-checkout-top h1{margin:3px 0;font-size:26px}.cp-checkout-steps{display:flex;margin-top:16px}.cp-step{flex:1;padding:10px;background:#f1f5f9;border-top:3px solid #cbd5e1;font-size:10px;font-weight:800}.cp-step.active{border-top-color:#f59e0b;background:#fffbeb}.cp-checkout-grid{display:grid;grid-template-columns:1fr 360px;gap:16px}.cp-check-card{background:#fff;border-radius:8px;padding:20px;margin-bottom:14px}.cp-check-card h2{font-size:18px;margin:0 0 14px}.cp-address{border:1px solid #cbd5e1;border-radius:7px;padding:12px;display:block;margin-bottom:9px}.cp-address:has(input:checked){border-color:#f59e0b;background:#fffbeb}.cp-pay-list{display:grid;gap:8px}.cp-pay{display:flex;align-items:center;gap:10px;border:1px solid #cbd5e1;border-radius:7px;padding:12px}.cp-pay:has(input:checked){border-color:#f59e0b;background:#fffbeb}.cp-pay b{font-size:12px}.cp-pay small{display:block;color:#64748b;margin-top:3px}.cp-check-card input[type=text],.cp-check-card select{width:100%;padding:11px;border:1px solid #b8c2cc;border-radius:6px}.cp-check-card button{width:100%;padding:13px;border:1px solid #f0b800;background:#ffd814;border-radius:8px;font-weight:900;font-size:14px}.cp-order-item{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #eef0f3;font-size:11px}.cp-order-summary{position:sticky;top:118px;height:max-content}.cp-total{font-size:21px;font-weight:900;display:flex;justify-content:space-between;padding-top:14px}.cp-secure{font-size:10px;color:#64748b;line-height:1.6;margin-top:10px}@media(max-width:900px){.cp-checkout-grid{grid-template-columns:1fr}.cp-order-summary{position:static}}@media(max-width:520px){.cp-checkout{padding:10px}.cp-check-card{padding:14px}.cp-checkout-steps{overflow:auto}.cp-step{min-width:140px}}
</style>
@endpush
@section('content')
<div class="cp-checkout"><div class="cp-checkout-shell"><section class="cp-checkout-top"><div style="font-size:10px;font-weight:900;letter-spacing:1.4px;color:#c45500">CHACHA 查查</div><h1>Secure checkout</h1><div class="cp-checkout-steps"><div class="cp-step active">1. Delivery</div><div class="cp-step active">2. Payment</div><div class="cp-step">3. Confirmation</div></div></section>@if($errors->any())<div class="notice error">@foreach($errors->all() as $e)<div>{{$e}}</div>@endforeach</div>@endif
<form method="POST" action="{{route('checkout.place')}}">@csrf<div class="cp-checkout-grid"><div><section class="cp-check-card"><h2>1. Delivery address</h2>@forelse($addresses as $a)<label class="cp-address"><input type="radio" name="address_id" value="{{$a->id}}" @checked($a->is_default) required> <strong>{{$a->recipient_name}}</strong><br><span style="font-size:11px;color:#475569;margin-left:22px">{{$a->phone}} • {{$a->address_line1}}, {{$a->city}}{{$a->is_default?' • Default':''}}</span></label>@empty<p>No saved address. Add one in <a href="{{route('customer.addresses')}}">Address Book</a>.</p>@endforelse</section>
<section class="cp-check-card"><h2>2. Payment method</h2><div class="cp-pay-list">@forelse($methods as $m)<label class="cp-pay"><input type="radio" name="payment_method_id" value="{{$m->id}}" required><span><b>{{$m->name}}</b><small>Available through Chacha Prime checkout</small></span></label>@empty<p>No payment methods are currently enabled.</p>@endforelse</div></section>
<section class="cp-check-card"><h2>3. Coupon / promotion</h2><input type="text" name="coupon_code" list="coupon-list" placeholder="Enter coupon code"><datalist id="coupon-list">@foreach($coupons as $coupon)<option value="{{$coupon->code}}"></option>@endforeach</datalist></section>
<section class="cp-check-card"><h2>Place order</h2><button @disabled($addresses->isEmpty()||$methods->isEmpty())>Place order securely</button><div class="cp-secure">Server-side validation checks stock, ownership of the address, coupon rules and enabled payment methods. Payment remains pending until a provider webhook confirms settlement.</div></section></div><aside class="cp-order-summary"><section class="cp-check-card"><h2>Order summary</h2>@foreach($products as $p)<div class="cp-order-item"><span>{{\Illuminate\Support\Str::limit($p->name,42)}} × {{$cart[$p->id]}}</span><strong>{{number_format($prices[$p->id]*$cart[$p->id],2)}} {{$p->currency}}</strong></div>@endforeach<div class="cp-total"><span>Total</span><span>{{number_format($total,2)}} {{ $products->first()->currency ?? "USD" }}</span></div><p class="cp-secure">Secure payment • Buyer protection • Seller fulfillment tracking</p><p style="font-size:10px;color:#64748b;margin:8px 0 0">All items in this checkout must use the same currency. Shipping and tax are currently calculated as 0 until marketplace shipping/tax rules are configured.</p></section></aside></div></form></div></div>
@endsection