@extends('layouts.storefront')
@section('title','Secure Checkout — Chacha Prime')
@push('styles')
<style>
.cp-checkout{background:#eaeded;min-height:calc(100vh - 104px);padding:20px}.cp-checkout-shell{max-width:1280px;margin:auto}.cp-checkout-top{background:#fff;padding:18px 22px;border-radius:8px;margin-bottom:14px}.cp-checkout-top h1{margin:3px 0;font-size:26px}.cp-marketplace-context{display:flex;flex-wrap:wrap;gap:6px 10px;align-items:center;margin-top:10px;font-size:10px;color:#64748b}.cp-marketplace-context strong{color:#0f172a}.cp-checkout-steps{display:flex;margin-top:16px}.cp-step{flex:1;padding:10px;background:#f1f5f9;border-top:3px solid #cbd5e1;font-size:10px;font-weight:800}.cp-step.active{border-top-color:#f59e0b;background:#fffbeb}.cp-checkout-grid{display:grid;grid-template-columns:1fr 360px;gap:16px}.cp-check-card{background:#fff;border-radius:8px;padding:20px;margin-bottom:14px}.cp-check-card h2{font-size:18px;margin:0 0 14px}.cp-address{border:1px solid #cbd5e1;border-radius:7px;padding:12px;display:block;margin-bottom:9px}.cp-address:has(input:checked){border-color:#f59e0b;background:#fffbeb}.cp-pay-list{display:grid;gap:8px}.cp-pay{display:flex;align-items:center;gap:10px;border:1px solid #cbd5e1;border-radius:7px;padding:12px}.cp-pay:has(input:checked){border-color:#f59e0b;background:#fffbeb}.cp-pay b{font-size:12px}.cp-pay small{display:block;color:#64748b;margin-top:3px}.cp-check-card input[type=text],.cp-check-card select{width:100%;padding:11px;border:1px solid #b8c2cc;border-radius:6px}.cp-check-card button{width:100%;padding:13px;border:1px solid #f0b800;background:#ffd814;border-radius:8px;font-weight:900;font-size:14px}.cp-vendor-list{display:grid;gap:10px}.cp-vendor-card{border:1px solid #dbe2e8;border-radius:8px;padding:12px;background:#fbfcfd}.cp-vendor-head,.cp-vendor-line,.cp-vendor-delivery{display:flex;justify-content:space-between;gap:12px;padding:6px 0;font-size:11px}.cp-vendor-head{border-bottom:1px solid #eef0f3;padding-top:0}.cp-vendor-delivery{margin-top:4px;padding:8px;background:#f1f5f9;border-radius:6px}.cp-order-item{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #eef0f3;font-size:11px}.cp-order-summary{position:sticky;top:118px;height:max-content}.cp-total{font-size:21px;font-weight:900;display:flex;justify-content:space-between;padding-top:14px}.cp-secure{font-size:10px;color:#64748b;line-height:1.6;margin-top:10px}@media(max-width:900px){.cp-checkout-grid{grid-template-columns:1fr}.cp-order-summary{position:static}}@media(max-width:520px){.cp-checkout{padding:10px}.cp-check-card{padding:14px}.cp-checkout-steps{overflow:auto}.cp-step{min-width:140px}}
 .cp-marketplace-note{display:flex;gap:10px;align-items:flex-start;background:#f8fafc;border:1px solid #dbe3ea;border-radius:8px;padding:12px;margin-bottom:12px;font-size:11px}.cp-marketplace-note b{display:block;margin-bottom:3px}.cp-vendor{border:1px solid #dbe3ea;border-radius:8px;padding:14px;margin-top:12px}.cp-vendor-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.cp-vendor-head strong{font-size:13px}.cp-vendor-meta{font-size:10px;color:#64748b;margin-top:3px}.cp-vendor-row{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-top:1px solid #eef0f3;font-size:11px}.cp-vendor-total{font-weight:900}.cp-delivery{margin-top:9px;padding:9px;background:#f8fafc;border-radius:6px;font-size:10px;color:#475569}.cp-country-pill{display:inline-block;border:1px solid #cbd5e1;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:800;margin-left:6px}@media(max-width:520px){.cp-vendor-head{display:block}.cp-country-pill{margin:6px 0 0}}\n</style>
@endpush
@section('content')
<div class="cp-checkout"><div class="cp-checkout-shell"><section class="cp-checkout-top"><div style="font-size:10px;font-weight:900;letter-spacing:1.4px;color:#c45500">CHACHA PRIME MARKETPLACE</div><h1>Secure checkout</h1><div class="cp-checkout-steps"><div class="cp-step active">1. Delivery</div><div class="cp-step active">2. Payment</div><div class="cp-step">3. Confirmation</div></div></section>@if($errors->any())<div class="notice error">@foreach($errors->all() as $e)<div>{{$e}}</div>@endforeach</div>@endif
<form method="POST" action="{{route('checkout.place')}}">@csrf<div class="cp-checkout-grid"><div><div class="cp-marketplace-note"><div><b>Marketplace delivery</b><span>Your order will be fulfilled for the selected marketplace country. Shipping, tax, stock and delivery estimates are calculated from marketplace rules.</span></div></div><section class="cp-check-card"><h2>1. Delivery address</h2>@forelse($addresses as $a)<label class="cp-address"><input type="radio" name="address_id" value="{{$a->id}}" @checked($a->is_default) required> <strong>{{$a->recipient_name}}</strong><br><span style="font-size:11px;color:#475569;margin-left:22px">{{$a->phone}} — {{$a->address_line1}}, {{$a->city}}{{$a->is_default?' — Default':''}}</span></label>@empty<p>No saved address. Add one in <a href="{{route('customer.addresses')}}">Address Book</a>.</p>@endforelse</section>
<section class="cp-check-card"><h2>2. Payment method</h2><div class="cp-pay-list">@forelse($methods as $m)<label class="cp-pay"><input type="radio" name="payment_method_id" value="{{$m->id}}" required><span><b>{{$m->name}}</b><small>Available through Chacha Prime checkout</small></span></label>@empty<p>No payment methods are currently enabled.</p>@endforelse</div></section>
<section class="cp-check-card"><h2>3. Seller delivery breakdown</h2><div class="cp-vendor-list">@foreach($vendorShipping as $vendorId=>$group)<div class="cp-vendor-card"><div class="cp-vendor-head"><strong>Seller #{{$vendorId}}</strong><span>{{number_format($group['subtotal'],2)}} {{strtoupper($currencies[$products->firstWhere('vendor_id',$vendorId)->id] ?? $products->first()->currency ?? 'USD')}}</span></div><div class="cp-vendor-line"><span>Items</span><strong>{{number_format($group['subtotal'],2)}}</strong></div><div class="cp-vendor-line"><span>Shipping</span><strong>{{number_format($group['shipping']['amount'] ?? 0,2)}}</strong></div><div class="cp-vendor-line"><span>Tax</span><strong>{{number_format($group['tax'] ?? 0,2)}}</strong></div><div class="cp-vendor-delivery"><span>Delivery</span><strong>{{ $group['shipping']['method'] ?? 'Standard delivery' }}{{($group['shipping']['min_days'] ?? null)!==null ? ' · '.$group['shipping']['min_days'].'–'.$group['shipping']['max_days'].' days' : ''}}</strong></div></div>@endforeach</div></section>
<section class="cp-check-card"><h2>4. Coupon / promotion</h2><input type="text" name="coupon_code" list="coupon-list" placeholder="Enter coupon code"><datalist id="coupon-list">@foreach($coupons as $coupon)<option value="{{$coupon->code}}"></option>@endforeach</datalist></section>
<section class="cp-check-card"><h2>5. Place order</h2><button @disabled($addresses->isEmpty()||$methods->isEmpty())>Place order securely</button><div class="cp-secure">Server-side validation checks stock, ownership of the address, coupon rules and enabled payment methods. Payment remains pending until a provider webhook confirms settlement.</div></section></div><aside class="cp-order-summary"><section class="cp-check-card"><h2>Order summary</h2>
@foreach($vendorShipping as $vendorId=>$group)
@php($vendor=optional($products->firstWhere('vendor_id',$vendorId))->vendor)
<div class="cp-vendor">
<div class="cp-vendor-head"><div><strong>{{ $vendor->business_name ?? $vendor->legal_name ?? 'Seller' }}</strong><div class="cp-vendor-meta">Seller fulfillment</div></div><span class="cp-country-pill">Marketplace country #{{$countryId}}</span></div>
@foreach($products->where('vendor_id',$vendorId) as $p)
<div class="cp-vendor-row"><span>{{IlluminateSupportStr::limit($p->name,42)}} × {{$cart[$p->id]}}</span><strong>{{number_format($prices[$p->id]*$cart[$p->id],2)}} {{$p->currency}}</strong></div>
@endforeach
<div class="cp-vendor-row"><span>Seller subtotal</span><strong>{{number_format($group['subtotal'],2)}} {{$currencies[$products->where('vendor_id',$vendorId)->first()->id] ?? ($products->first()->currency ?? 'USD')}}</strong></div>
<div class="cp-vendor-row"><span>Shipping</span><strong>{{number_format($group['shipping']['amount'] ?? 0,2)}} {{$products->where('vendor_id',$vendorId)->first()->currency ?? 'USD'}}</strong></div>
<div class="cp-vendor-row"><span>Tax</span><strong>{{number_format($group['tax'] ?? 0,2)}} {{$products->where('vendor_id',$vendorId)->first()->currency ?? 'USD'}}</strong></div>
<div class="cp-vendor-row cp-vendor-total"><span>Seller total</span><strong>{{number_format($group['subtotal'] + ($group['shipping']['amount'] ?? 0) + ($group['tax'] ?? 0),2)}} {{$products->where('vendor_id',$vendorId)->first()->currency ?? 'USD'}}</strong></div>
<div class="cp-delivery">{{ $group['shipping']['method'] ?? 'Standard marketplace delivery' }} @if(!empty($group['shipping']['min_days'])) · Estimated {{ $group['shipping']['min_days'] }}–{{ $group['shipping']['max_days'] }} days @endif</div>
</div>
@endforeach
<div style="display:flex;justify-content:space-between;padding-top:12px;font-size:11px"><span>Subtotal</span><strong>{{number_format($total,2)}} {{ $products->first()->currency ?? "USD" }}</strong></div>
<div style="display:flex;justify-content:space-between;padding-top:8px;font-size:11px"><span>Total shipping</span><strong>{{number_format($shippingTotal ?? 0,2)}} {{ $products->first()->currency ?? "USD" }}</strong></div>
<div style="display:flex;justify-content:space-between;padding-top:8px;font-size:11px"><span>Total tax</span><strong>{{number_format($taxTotal ?? 0,2)}} {{ $products->first()->currency ?? "USD" }}</strong></div>
<div class="cp-total"><span>Grand total</span><span>{{number_format($total + ($shippingTotal ?? 0) + ($taxTotal ?? 0),2)}} {{ $products->first()->currency ?? "USD" }}</span></div>
<p class="cp-secure">Secure payment • Buyer protection • Seller fulfillment tracking</p>
<p style="font-size:10px;color:#64748b;margin:8px 0 0">Shipping and tax are calculated from the selected marketplace country and configured zone/rate rules.</p></section></aside></div></form></div></div>
@endsection