@extends('layouts.storefront')
@section('title','Group Buying — CHACHA 查查')
@push('styles')
<style>
.cp-gb{background:#eaeded;min-height:calc(100vh - 104px);padding:20px}.cp-gb-shell{max-width:1450px;margin:auto}.cp-gb-hero{background:linear-gradient(110deg,#071a31,#075985,#2563eb);border-radius:8px;color:#fff;padding:30px}.cp-gb-hero h1{font-size:34px;margin:7px 0}.cp-gb-hero p{margin:0;color:#dbeafe;font-size:13px}.cp-gb-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:16px}.cp-gb-card{background:#fff;border-radius:8px;padding:15px}.cp-gb-card .tag{font-size:9px;font-weight:900;color:#2563eb}.cp-gb-card h2{font-size:15px;line-height:1.4;margin:8px 0}.cp-gb-card strong{font-size:21px}.cp-gb-card small{display:block;color:#64748b;font-size:10px;margin-top:7px}.cp-gb-actions{display:flex;gap:7px;margin-top:14px}.cp-gb-actions a,.cp-gb-actions button{padding:9px 11px;border-radius:7px;text-decoration:none;font-size:10px;font-weight:800;border:1px solid #d5d9d9;background:#fff;color:#111}.cp-gb-actions .join{background:#2563eb;color:#fff;border-color:#2563eb}.cp-gb-bar{height:7px;background:#e5e7eb;border-radius:99px;margin-top:11px;overflow:hidden}.cp-gb-bar i{display:block;height:100%;background:#2563eb}@media(max-width:1000px){.cp-gb-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.cp-gb{padding:10px}.cp-gb-grid{grid-template-columns:1fr}.cp-gb-hero{padding:22px}}
</style>
@endpush
@section('content')
<div class="cp-gb"><div class="cp-gb-shell">
<section class="cp-gb-hero"><div style="font-size:10px;font-weight:900;letter-spacing:1.6px">BUY TOGETHER • SAVE TOGETHER</div><h1>Group Buying</h1><p>Active offers from Chacha Prime sellers — join together and unlock seller-set group prices.</p></section>
<div class="cp-gb-grid">@forelse($campaigns as $c)@php $joined=DB::table('group_buying_participants')->where('campaign_id',$c->id)->whereIn('status',['reserved','confirmed'])->sum('quantity'); $pct=min(100,round(($joined/max(1,(int)$c->target_participants))*100)); @endphp
<article class="cp-gb-card"><span class="tag">GROUP OFFER</span><h2>{{$c->title}}</h2><strong>{{$c->offer_price}} {{$c->currency}}</strong><small>{{$c->target_participants}} buyer target • {{$joined}} joined • Ends {{$c->ends_at}}</small><div class="cp-gb-bar"><i style="width:{{$pct}}%"></i></div><div class="cp-gb-actions"><a href="{{route('product',$c->product_id)}}">View Product</a>@auth<form method="POST" action="{{route('customer.group-buying.join',$c->id)}}">@csrf<button class="join">Join Group</button></form>@else<a class="join" href="{{route('auth.login')}}">Sign in to Join</a>@endauth</div></article>
@empty<div style="background:#fff;padding:25px;border-radius:8px">No active group buying campaigns right now.</div>@endforelse</div>{{$campaigns->links()}}
</div></div>
@endsection