@extends('layouts.storefront')
@section('title','Live Shopping — CHACHA 查查')
@push('styles')
<style>
.cp-live{background:#eaeded;min-height:calc(100vh - 104px);padding:20px}.cp-live-shell{max-width:1450px;margin:auto}.cp-live-hero{background:linear-gradient(110deg,#170b2c,#5b246f,#c026d3);border-radius:8px;color:#fff;padding:30px}.cp-live-hero h1{font-size:34px;margin:7px 0}.cp-live-hero p{margin:0;color:#f5d0fe;font-size:13px}.cp-live-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:16px}.cp-live-card{background:#fff;border-radius:8px;padding:12px}.cp-live-card .video{aspect-ratio:16/9;background:#111827;border-radius:6px;overflow:hidden}.cp-live-card iframe{width:100%;height:100%;border:0}.cp-live-card h2{font-size:15px;margin:10px 0 4px}.cp-live-card p{font-size:11px;color:#64748b}.livebadge{font-size:9px;font-weight:900;color:#dc2626}@media(max-width:900px){.cp-live-grid{grid-template-columns:1fr 1fr}}@media(max-width:550px){.cp-live{padding:10px}.cp-live-grid{grid-template-columns:1fr}.cp-live-hero{padding:22px}}
</style>
@endpush
@section('content')
<div class="cp-live"><div class="cp-live-shell"><section class="cp-live-hero"><div style="font-size:10px;font-weight:900;letter-spacing:1.6px">LIVE COMMERCE</div><h1>Live Shopping</h1><p>Watch Chacha Prime sellers stream products and shop in real time.</p></section><div class="cp-live-grid">@forelse($streams as $s)<article class="cp-live-card"><div class="video">@if($s->youtube_video_id)<iframe src="https://www.youtube.com/embed/{{rawurlencode($s->youtube_video_id)}}" title="{{e($s->title)}}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>@endif</div><span class="livebadge">● {{$s->status==='live'?'LIVE NOW':'UPCOMING'}}</span><h2>{{$s->title}}</h2><p>{{$s->business_name}}</p></article>@empty<div style="background:#fff;padding:25px;border-radius:8px">No live shopping streams scheduled.</div>@endforelse</div>{{$streams->links()}}</div></div>
@endsection