@extends('layouts.storefront')
@section('title',$product->name)
@push('styles')
<style>
.cp-pdp{background:#fff;min-height:calc(100vh - 104px);padding:24px}.cp-pdp-shell{max-width:1400px;margin:auto}.cp-bread{font-size:11px;color:#64748b;margin-bottom:16px}.cp-pdp-grid{display:grid;grid-template-columns:55% 45%;gap:30px}.cp-gallery{display:grid;grid-template-columns:88px 1fr;gap:14px}.cp-thumbs{display:grid;gap:9px;align-content:start}.cp-thumb{border:1px solid #d5d9d9;background:#fff;border-radius:5px;padding:5px;height:82px}.cp-thumb img{width:100%;height:100%;object-fit:contain}.cp-mainimg{height:520px;background:#fff;display:grid;place-items:center;border-radius:8px}.cp-mainimg img{max-width:100%;max-height:100%;object-fit:contain}.cp-noimg{font-size:90px;color:#cbd5e1}.cp-pdp-info h1{font-size:29px;line-height:1.2;margin:0 0 7px}.cp-seller{font-size:12px;color:#1769aa}.cp-stars{color:#b45309;font-size:12px;margin:10px 0}.cp-price{font-size:30px;font-weight:700;margin:8px 0}.cp-price small{font-size:12px;color:#64748b;font-weight:500}.cp-box{border:1px solid #d5d9d9;border-radius:8px;padding:17px;margin-top:15px}.cp-box h3{font-size:15px;margin:0 0 12px}.cp-tier{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eee;font-size:12px}.cp-buy{display:flex;gap:10px;align-items:center;margin-top:16px}.cp-buy input{width:90px;padding:11px;border:1px solid #a6a6a6;border-radius:7px}.cp-buy button{padding:12px 22px;border:1px solid #f0b800;background:#ffd814;border-radius:8px;font-weight:800;cursor:pointer}.cp-meta{font-size:12px;color:#475569;line-height:1.7}.cp-description{margin-top:25px;border-top:1px solid #ddd;padding-top:20px}.cp-description h2{font-size:22px}.cp-description p{line-height:1.7;color:#334155}@media(max-width:850px){.cp-pdp{padding:12px}.cp-pdp-grid{grid-template-columns:1fr}.cp-mainimg{height:380px}.cp-gallery{grid-template-columns:70px 1fr}}
</style>
@endpush
@section('content')
<div class="cp-pdp"><div class="cp-pdp-shell">
<div class="cp-bread">CHACHA 查查 / {{$product->category?->name ?? 'Marketplace'}} / Product</div>
<div class="cp-pdp-grid">
<div class="cp-gallery"><div class="cp-thumbs">@foreach($product->images as $img)<div class="cp-thumb"><img src="{{asset('storage/'.$img->path)}}" alt="{{e($img->alt_text ?: $product->name)}}"></div>@endforeach</div><div class="cp-mainimg">@if($product->images->count())<img src="{{asset('storage/'.$product->images->first()->path)}}" alt="{{e($product->name)}}">@else<span class="cp-noimg">□</span>@endif</div></div>
<div class="cp-pdp-info"><h1>{{$product->name}}</h1><div class="cp-seller">Sold by {{$product->vendor?->business_name ?? 'Marketplace Seller'}}</div><div class="cp-stars">★ Marketplace listing</div><div class="cp-price">{{$price}} {{$product->currency}} <small>{{strtoupper($customerType)}} customer price</small></div><div class="cp-meta">Base retail price: {{$product->retail_price}} {{$product->currency}}<br>Stock available: {{$product->stock}}</div>
@if($tiers->count())<div class="cp-box"><h3>Volume Pricing</h3>@foreach($tiers as $t)<div class="cp-tier"><span>{{$t->min_quantity}}@if($t->max_quantity)–{{$t->max_quantity}}@else+@endif units</span><strong>{{$t->price}} {{$product->currency}}</strong></div>@endforeach</div>@endif
<div class="cp-buy"><form method="POST" action="{{route('cart.add',$product->id)}}" style="display:flex;gap:10px;align-items:center">@csrf<input name="quantity" type="number" min="1" max="{{$product->stock}}" value="1"><button>Add to Cart</button></form></div>
</div></div>
<div class="cp-description"><h2>About this product</h2><p>{{$product->description ?: $product->short_description}}</p></div>
</div></div>
@endsection