@extends('layouts.storefront')
@section('title','Products — CHACHA 查查')
@push('styles')
<style>
.cp-shop{background:#eaeded;min-height:calc(100vh - 104px);padding:18px}.cp-shop-shell{max-width:1500px;margin:auto}.cp-shop-head,.cp-shop-panel{background:#fff;border-radius:7px;padding:18px}.cp-shop-head{display:flex;justify-content:space-between;align-items:center;gap:15px}.cp-shop-head h1{margin:4px 0;font-size:27px}.cp-shop-head p{margin:0;color:#64748b;font-size:12px}.cp-shop-tools{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cp-shop-tools input,.cp-shop-tools select{padding:11px;border:1px solid #cbd5e1;border-radius:4px;font-size:12px}.cp-shop-tools input{flex:1;min-width:240px}.cp-shop-tools button{background:#ffd814;border:1px solid #f0b800;border-radius:4px;padding:10px 18px;font-weight:800}.cp-shop-layout{display:grid;grid-template-columns:210px 1fr;gap:15px}.cp-shop-side{background:#fff;border-radius:7px;padding:16px;height:max-content}.cp-shop-side h3{font-size:14px;margin:0 0 12px}.cp-shop-side a{display:block;padding:8px 0;color:#334155;text-decoration:none;font-size:12px}.cp-shop-side a:hover{color:#c45500}.cp-shop-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.cp-shop-product{background:#fff;border-radius:7px;padding:13px;text-decoration:none;color:#111;min-width:0}.cp-shop-image{height:210px;background:#f7f7f7;display:grid;place-items:center;border-radius:5px;overflow:hidden}.cp-shop-image img{width:100%;height:100%;object-fit:contain}.cp-shop-image .noimg{font-size:50px;color:#cbd5e1}.cp-shop-product h3{font-size:13px;line-height:1.4;margin:9px 0 4px}.cp-shop-product .seller{font-size:10px;color:#64748b}.cp-shop-product .price{font-size:18px;font-weight:800;margin-top:7px}.cp-shop-product .rating{font-size:10px;color:#b45309;margin-top:4px}.cp-shop-product .stock{font-size:10px;color:#047857;margin-top:4px}.cp-shop-sections{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:15px 0}.cp-shop-section{background:#fff;border-radius:7px;padding:15px;text-decoration:none;color:#111}.cp-shop-section b{font-size:15px}.cp-shop-section span{display:block;color:#64748b;font-size:10px;margin-top:5px}@media(max-width:1100px){.cp-shop-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.cp-shop-layout{grid-template-columns:1fr}.cp-shop-side{display:none}.cp-shop-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.cp-shop{padding:10px}.cp-shop-grid{grid-template-columns:1fr 1fr}.cp-shop-image{height:155px}.cp-shop-product{padding:9px}.cp-shop-head{align-items:flex-start;flex-direction:column}}
</style>
@endpush
@section('content')
<div class="cp-shop"><div class="cp-shop-shell">
<section class="cp-shop-head"><div><div style="font-size:10px;font-weight:900;letter-spacing:1.5px;color:#c45500">CHACHA 查查 MARKETPLACE</div><h1>All Products</h1><p>Products from all approved marketplace sellers.</p></div><a href="{{route('cart')}}" class="button button-dark">Cart</a></section>
<form method="GET" class="cp-shop-panel cp-shop-tools"><input name="q" value="{{$q}}" placeholder="Search products, brands and more"><select name="category"><option value="">All Categories</option>@foreach($categories as $cat)<option value="{{$cat->id}}" @selected((int)$category===$cat->id)>{{$cat->name}}</option>@endforeach</select><button>Search</button></form>
<div class="cp-shop-sections"><a class="cp-shop-section" href="{{route('group-buying')}}"><b>👥 Group Buying</b><span>All active seller offers in one place →</span></a><a class="cp-shop-section" href="{{route('live')}}"><b>● Live Commerce</b><span>Watch sellers and shop live →</span></a><a class="cp-shop-section" href="{{route('shop')}}?deals=1"><b>🏷 Coupons & Deals</b><span>Browse marketplace promotions →</span></a></div>
<div class="cp-shop-layout"><aside class="cp-shop-side"><h3>Departments</h3><a href="{{route('shop')}}">All Products</a><a href="{{route('group-buying')}}">Group Buying</a><a href="{{route('live')}}">Live Shopping</a><a href="{{route('shop')}}?deals=1">Deals & Coupons</a><a href="{{route('shop')}}">B2B Marketplace</a><a href="{{route('shop')}}">B2C Marketplace</a></aside>
<section><div class="cp-shop-grid">@forelse($products as $p)<a class="cp-shop-product" href="{{route('product',$p->id)}}"><div class="cp-shop-image">@if($p->images->count())<img src="{{asset('storage/'.$p->images->first()->path)}}" alt="{{e($p->name)}}">@else<span class="noimg">□</span>@endif</div><h3>{{IlluminateSupportStr::limit($p->name,62)}}</h3><div class="seller">{{$p->vendor?->business_name ?? 'Marketplace Seller'}}</div><div class="price">{{$p->currency}} {{number_format((float)$p->retail_price,2)}}</div><div class="rating">★ Marketplace product</div><div class="stock">{{$p->stock>0?'In Stock':'Currently unavailable'}}</div></a>@empty<div class="cp-shop-panel">No published products found.</div>@endforelse</div><div style="margin-top:18px">{{$products->links()}}</div></section></div>
</div></div>
@endsection